// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
var aws_app_analytics = 'enable';
var aws_cloud_logic = 'enable';
var aws_cloud_logic_custom = [{"id":"bcg4169d55","name":"WorkoutsCRUD","description":"","endpoint":"https://bcg4169d55.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/Workouts","/Workouts/123","/path-5fa","/path-5fa/123"]},{"id":"lmcwf3zdze","name":"sampleCloudApi","description":"","endpoint":"https://lmcwf3zdze.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/items","/items/123"]}];
var aws_cognito_identity_pool_id = 'us-east-1:13110393-9b75-4ced-892a-5efefa8ad0cb';
var aws_cognito_region = 'us-east-1';
var aws_content_delivery = 'enable';
var aws_content_delivery_bucket = 'fitpower-hosting-mobilehub-2075586205';
var aws_content_delivery_bucket_region = 'us-east-1';
var aws_content_delivery_cloudfront = 'enable';
var aws_content_delivery_cloudfront_domain = 'd322q6emwzmn0j.cloudfront.net';
var aws_dynamodb = 'enable';
var aws_dynamodb_all_tables_region = 'us-east-1';
var aws_dynamodb_table_schemas = [{"tableName":"fitpower-mobilehub-2075586205-AWSMobileTable","attributes":[{"name":"teamId","type":"S"},{"name":"personId","type":"S"},{"name":"email","type":"S"},{"name":"personName","type":"S"},{"name":"phone","type":"S"}],"indexes":[{"indexName":"personName-index","hashKey":"teamId","rangeKey":"personName"}],"region":"us-east-1","hashKey":"teamId","rangeKey":"personId"},{"tableName":"fitpower-mobilehub-2075586205-Workouts","attributes":[{"name":"userId","type":"S"},{"name":"powerGenerated","type":"NS"}],"indexes":[],"region":"us-east-1","hashKey":"userId"}];
var aws_mandatory_sign_in = 'enable';
var aws_mobile_analytics_app_id = 'f6385940053c4d6d9949488db75c6ec7';
var aws_mobile_analytics_app_region = 'us-east-1';
var aws_project_id = '0cd2feb2-0ae9-4367-9bb2-3f74e869d0cb';
var aws_project_name = 'fitpower-2018-11-28-03-22-23';
var aws_project_region = 'us-east-1';
var aws_resource_bucket_name = 'fitpower-deployments-mobilehub-2075586205';
var aws_resource_name_prefix = 'fitpower-mobilehub-2075586205';
var aws_sign_in_enabled = 'enable';
var aws_user_pools = 'enable';
var aws_user_pools_id = 'us-east-1_HqtN8NPsq';
var aws_user_pools_mfa_type = 'ON';
var aws_user_pools_web_client_id = '3ffr81fglrkc01001bds9d5nho';

AWS.config.region = aws_project_region;
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: aws_cognito_identity_pool_id
  }, {
    region: aws_cognito_region
  });
AWS.config.update({customUserAgent: 'MobileHub v0.1'});
